name: Clang-Tidy

on:
  pull_request:
    branches: [ master ]
    paths: [ '**.cpp', '**.h' ]

  push:
    branches: [ master ]
    paths: [ '**.cpp', '**.h' ]

jobs:
  tidy:
    name: Clang-Tidy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - name: Install dependencies and clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y libfmt-dev gettext clang-tidy-12
      - name: Setup clang-tidy
        run: |
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-12 100
          sudo update-alternatives --install /usr/bin/clang-tidy-diff clang-tidy-diff /usr/bin/clang-tidy-diff-12.py 100
      - name: Prepare compile_commands.json
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
      - name: Create results directory
        run: |
          mkdir clang-tidy-result
      - name: Analyze
        run: |
          git diff -U0 HEAD^ | clang-tidy-diff -p1 -path build -export-fixes clang-tidy-result/fixes.yml
      - name: Save PR metadata
        run: |
          echo ${{ github.event.number }} > clang-tidy-result/pr-id.txt
          echo ${{ github.event.pull_request.head.repo.full_name }} > clang-tidy-result/pr-head-repo.txt
          echo ${{ github.event.pull_request.head.ref }} > clang-tidy-result/pr-head-ref.txt
      - uses: actions/upload-artifact@v2
        with:
          name: clang-tidy-result
          path: clang-tidy-result/
