name: CMake

on: [ push, pull_request ]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Linux GCC
            os: ubuntu-latest
            cc: gcc
            cxx: g++
            version: 11
            dependencies: libfmt-dev gcc-11 g++-11
          - name: Linux CLANG
            os: ubuntu-latest
            cc: clang
            cxx: clang++
            version: 12
            dependencies: libfmt-dev clang-12 clang++-12
    name: CMake (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies (Linux)
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.config.dependencies }}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/${{ matrix.config.cc }}-${{ matrix.config.version }} 200 --slave /usr/bin/g++ g++ /usr/bin/${{ matrix.config.cxx }}-${{ matrix.config.version }}
      - name: Install dependencies (macOS)
        if: ${{ matrix.config.os == 'macos-latest' }}
        run: |
          brew install ${{ matrix.config.dependencies }}
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j2
      - name: Install
        run: |
          sudo cmake --install build
